[build]
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/jev/shot"
  to = "/.netlify/functions/jev-shot"
  status = 200
